#  _____ _ _            _____ _____ _____
# |   __| |_|___ ___   |  _  |     |  _  |
# |__   | | |  _|   |  |     |  |  |   __|
# |_____|_|_|_| |_|_|  |__|__|_____|__|
#
# SlimACAPI Configuration
# Version: 1.0.0
# Author: wwishh

# ===========================================
# Alert System Configuration
# ===========================================
alerts:
  # Enable or disable the alert system
  # When enabled, staff members will receive notifications about potential violations
  enabled: true
  # Permission required to receive and manage alerts
  permission: "slimac.alerts"

# ===========================================
# Violation Management
# ===========================================
violations:
  # Whether to reset violations when a player disconnects
  # true: Violations are cleared on disconnect
  # false: Violations persist between sessions
  reset-on-disconnect: true
  # Maximum violations before taking action
  # Increase this value if you experience false positives
  max-violations: 20

# ===========================================
# Database Configuration
# ===========================================
database:
  # Database type to use
  # Options: "sqlite" or "mysql"
  # SQLite: Lightweight, file-based database (recommended for small servers)
  # MySQL: Better for larger servers or server networks
  type: "sqlite"

  # MySQL Configuration
  # Only used if type is set to "mysql"
  mysql:
    host: "localhost"
    port: 3306
    database: "anticheat"
    username: "root"
    password: ""

# ===========================================
# Ping Management
# ===========================================
ping:
  # Enable or disable ping checking
  enabled: true
  # Maximum allowed ping in milliseconds
  # Players exceeding this will trigger defined actions
  max-ping: 500
  # How often to check player ping (in seconds)
  check-interval: 5

  # Actions to take when ping exceeds limit
  actions:
    # Whether to kick players with high ping
    kick: true
    # Kick message (supports color codes)
    # Variables: {max-ping}, {ping}
    kick-message: "&cKicked for High Ping\n&fMaximum allowed: &e{max-ping}ms\n&fYour ping: &e{ping}ms"
    # Notify staff members about high ping
    notify-staff: true
    # Optional command to execute
    # Variables: {player}, {ping}, {max-ping}
    # Leave empty to disable
    command: ""

  # Permission to bypass ping checks
  bypass-permission: "slimac.ping.bypass"

# ===========================================
# Ping Compensation System
# ===========================================
ping-compensation:
  # Enable or disable ping compensation
  enabled: true
  # Maximum compensation in milliseconds
  # Prevents excessive compensation for very high ping
  max-compensation: 150

  # Compensation mode
  # ADAPTIVE: Dynamically adjusts based on ping history
  # FIXED: Uses current ping value directly
  mode: "ADAPTIVE"

  # Compensation factor (0.0 to 1.0)
  # 1.0: Full compensation
  # 0.5: Half compensation
  # 0.0: No compensation
  compensation-factor: 0.75

  # Number of ping values to keep in history
  # Used for adaptive compensation calculations
  history-size: 20

  # Update interval in server ticks (20 ticks = 1 second)
  update-interval: 1

  # Enable detailed debug logging
  debug: false