# SlimACAPI Configuration

# Alert Settings
alerts:
  enabled: true
  permission: "slimac.alerts"

# Violation Settings
violations:
  reset-on-disconnect: true
  max-violations: 20

# Database Settings
database:
  type: "sqlite" # sqlite/mysql
  mysql:
    host: "localhost"
    port: 3306
    database: "anticheat"
    username: "root"
    password: ""

# Ping Settings
ping:
  enabled: true
  max-ping: 500
  check-interval: 5 # en segundos
  actions:
    kick: true
    kick-message: "&cHas sido expulsado por ping alto\n&fPing máximo permitido: &e{max-ping}ms\n&fTu ping: &e{ping}ms"
    notify-staff: true
    command: "" # comando opcional para ejecutar (dejar vacío para deshabilitar)
  bypass-permission: "slimac.ping.bypass"