name: SlimAPI
version: '1.0.0'
main: com.wish.API
authors: [wwishh]
description: API for AntiCheat check plugins

commands:
  alerts:
    description: Toggle anticheat alerts
    usage: /alerts
    permission: slimac.alerts
  slimapi:
    description: Administrative commands for anticheat
    usage: /slimapi reload
    permission: slimac.admin

permissions:
  slimac.alerts:
    description: Allows viewing anticheat alerts
    default: op
  slimac.admin:
    description: Allows using administrative commands
    default: op
    children:
      slimac.alerts: true
  slimac.bypass.forge:
    description: Allows bypassing Forge client detection
    default: op
  slimac.bypass.fabric:
    description: Allows bypassing Fabric client detection
    default: op