name: SlimAPI
version: '1.0.0'
main: com.wish.API
authors: [wwishh]
description: API for AntiCheat check plugins

commands:
  alerts:
    description: Activa/desactiva las alertas del anticheat
    usage: /alerts
    permission: slimac.alerts
  slimapi:
    description: Comandos administrativos del anticheat
    usage: /slimapi reload
    permission: slimac.admin

permissions:
  slimac.alerts:
    description: Permite ver las alertas del anticheat
    default: op
  slimac.admin:
    description: Permite usar comandos administrativos
    default: op
    children:
      slimac.alerts: true